apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.postgresService.serviceName }}
  namespace: {{ .Values.namespace.db }}
spec:
  selector:
    app: {{ .Values.postgresService.selectorLabel }}
  ports:
    - port: {{ .Values.postgresService.port }}
      targetPort: {{ .Values.postgresService.targetPort }}
