apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Values.appName }}-pdb
  namespace: {{ .Values.apiServer.namespace }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: {{ .Values.appName }}
