apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.apiServer.serviceAccountName }}
  namespace: {{ .Values.apiServer.namespace }}
automountServiceAccountToken: {{ .Values.apiServer.automountToken }}
