apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.loadbalancer.serviceName }}
  namespace: {{ .Values.namespace.app }}
spec:
  type: {{ .Values.loadbalancer.serviceType }}
  selector:
    app: {{ .Values.loadbalancer.appLabel }}
  ports:
    - protocol: TCP
      port: {{ .Values.loadbalancer.servicePort }}
      targetPort: {{ .Values.loadbalancer.targetPort }}
