apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.clouddnsSecret.name }}
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  # This will be populated by Terraform
  {{ .Values.clouddnsSecret.keyName }}: {{ .Values.clouddnsSecretKeyData | quote }}
